# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#
production:
  piwik:
    id_site: 3 
    url: piwik.klaus-meyer.net
    use_async: false
    disabled: false

development:
  piwik:
    id_site: 3 
    url: piwik.klaus-meyer.net
    use_async: false
    disabled: true 

test:
  piwik:
    id_site: 3 
    url: piwik.klaus-meyer.net
    use_async: false
    disabled: true
